apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: AuthServer
metadata:
  name: $TAP_AUTH_SERVER_NAME
  namespace: $TAP_DEV_NAMESPACE
  labels:
    name: $TAP_AUTH_SERVER_NAME
  annotations:
    sso.apps.tanzu.vmware.com/allow-client-namespaces: $TAP_DEV_NAMESPACE
    sso.apps.tanzu.vmware.com/allow-unsafe-issuer-uri: ""
    sso.apps.tanzu.vmware.com/allow-unsafe-identity-provider: ""
spec:
  tls:
    issuerRef:
      name: letsencrypt-live
      kind: ClusterIssuer
  replicas: 1
  tokenSignature:
    signAndVerifyKeyRef:
      name: $TAP_AUTH_SERVER_NAME-signing-key
  identityProviders:
    - name: internal
      internalUnsafe:
        users:
          - username: admin
            password: admin
            roles:
              - customer
              - admin
          - username: user
            password: user
            roles:
              - customer
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: $TAP_AUTH_SERVER_NAME-signing-key
  namespace: $TAP_DEV_NAMESPACE
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)
---
apiVersion: v1
kind: Service
metadata:
  name: $TAP_AUTH_SERVER_NAME
  namespace: $TAP_DEV_NAMESPACE
spec:
  selector:
    app.kubernetes.io/part-of: $TAP_AUTH_SERVER_NAME
    app.kubernetes.io/component: authorization-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: $TAP_AUTH_SERVER_NAME
  namespace: $TAP_DEV_NAMESPACE
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: $TAP_AUTH_SERVER_NAME
          port: 80
  virtualhost:
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - "*"
      allowHeaders:
        - "*"
    fqdn: $TAP_AUTH_SERVER_NAME-$TAP_DEV_NAMESPACE.$TAP_DEV_ENVIRONMENT.$TAP_MASTER_DOMAIN
    tls:
      secretName: $TAP_AUTH_SERVER_SECRET_NAME
