apiVersion: v1
kind: Secret
metadata:
  name: observability-binding-compatible
type: Opaque
stringData:
  type: wavefront
  uri: $WAVEFRONT_API_URI
  api-token: $WAVEFRONT_API_TOKEN
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: observability-binding-compatible
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: observability-binding-compatible
