apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: Spring Cloud Architecture on TAP frontend
  tags:
    - sc-architecture
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=frontend"
    "backstage.io/techdocs-ref": dir:../
spec:
  type: service
  lifecycle: experimental
  owner: tanzu-shop-team
  system: tanzu-shop
  dependsOn:
    - Component:gateway
  consumesApis:
    - gateway-dev.tap-next.blah.cloud
