apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: frontend
  labels:
    app.kubernetes.io/part-of: frontend
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/min-scale: "1"
  - name: testing_pipeline_params
    value:
      source-sub-path: frontend
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: angular
      apps.tanzu.vmware.com/pipeline: test
  source:
    git:
      url: https://github.com/benwilcock/spring-cloud-demo-tap.git
      ref:
        branch: main
    subPath: frontend
  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: build
    - name: BP_WEB_SERVER
      value: nginx
    - name: BP_WEB_SERVER_ROOT
      value: dist/frontend
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: "true"